import Head from 'next/head'
import Product from '../components/Product'

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Home | Ecommerce Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Next.js Ecommerce" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container'>
        <h1 className='sectionTitle'>Our Product</h1>
        <div className='main'>
        {
          products.map(product=> <Product key={product.id} product={product}/> )
        }
        </div>
      </main>
    </div>
  )
}


// getInitialProps is a function that is called on server side and client side.
export async function getStaticProps() {
  const req = await fetch("https://fakestoreapi.com/products");
  const products = await req.json();

  return {
    props: {products}
  }
}


